### ISSUE TITLE
file format for point cloud file 

### ISSUE THREAD

**Issue by maxsw02** [simonzhang00/ripser-plusplus#12]
What is the formatting of the pointcloud file? I opened up the example file it had a six columns. I was a big confused.

**Comment by simonzhang00** [comment]
As you can see from [here](https://github.com/simonzhang00/ripser-plusplus/blob/master/ripserplusplus/ripser%2B%2B.cu#L3482): each line in your case is a 
6 dimensional point represented by 6 numbers in the reals.

The format is a list of $d$ floating points, each line represents point in the point cloud. A Numpy matrix can also be used with the python bindings. It has shape $n \times d$ where $n$ is the number of points and $d$ is the dimension of the space where the points lie.
